# Generated by Django 4.2.4 on 2023-09-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detail', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
                ('image_count', models.IntegerField()),
                ('order', models.IntegerField()),
                ('payment', models.CharField(max_length=200)),
                ('shipping_port', models.CharField(max_length=200)),
                ('lead_time', models.IntegerField()),
                ('material', models.CharField(max_length=200)),
                ('product_size', models.CharField(max_length=200)),
                ('sample_time', models.IntegerField()),
                ('tag', models.CharField(max_length=200)),
                ('product_url', models.CharField(max_length=200)),
            ],
        ),
    ]
